# Workshop Week 7 - Minhashing

In this workshop you will practice with various exercises related to techniques to determine the similarity between large collections of documents. Read the lecture material related to week 7. Some of the exercises in this workshop were mentioned in the lecture.

For this exercise you will use the documents in the NLTK Gutenberg corpus. The following code demonstrates how to read the documents of the Gutenberg corpus.

In [1]:
import nltk
nltk.download('gutenberg')

[nltk_data] Downloading package gutenberg to /root/nltk_data...
[nltk_data]   Unzipping corpora/gutenberg.zip.


True

In [2]:
from nltk.corpus import gutenberg
gutenberg.fileids()

['austen-emma.txt',
 'austen-persuasion.txt',
 'austen-sense.txt',
 'bible-kjv.txt',
 'blake-poems.txt',
 'bryant-stories.txt',
 'burgess-busterbrown.txt',
 'carroll-alice.txt',
 'chesterton-ball.txt',
 'chesterton-brown.txt',
 'chesterton-thursday.txt',
 'edgeworth-parents.txt',
 'melville-moby_dick.txt',
 'milton-paradise.txt',
 'shakespeare-caesar.txt',
 'shakespeare-hamlet.txt',
 'shakespeare-macbeth.txt',
 'whitman-leaves.txt']

The previous code lists all the documents of the Gutenberg corpus. You can see that it is a very small collection but it will suffice for the exercises in this workshop. The following code shows how you can read the text of one document.

In [3]:
emma = gutenberg.raw('austen-emma.txt')
emma[:200]

'[Emma by Jane Austen 1816]\n\nVOLUME I\n\nCHAPTER I\n\n\nEmma Woodhouse, handsome, clever, and rich, with a comfortable home\nand happy disposition, seemed to unite some of the best blessings\nof existence; an'

## Shingling

The following code can be used to find the set of k-shingles for a document.

In [4]:
def k_shingles(text, k):
    return set(nltk.ngrams(text, k))

In [5]:
k_shingles(emma, 3)

{('b', 'b', 'y'),
 ('p', 't', 'e'),
 ('"', 'a', 'b'),
 ('e', 'l', '\n'),
 ('n', ' ', 'L'),
 ('b', 'e', '?'),
 ('M', 'y', 's'),
 ('a', 'c', 'l'),
 ('e', '!', ' '),
 ('m', ' ', 't'),
 ('n', ' ', '_'),
 ('n', 'k', ','),
 ('s', 'i', 'o'),
 ('\n', 'E', 'x'),
 ('!', ' ', 'L'),
 ('r', ')', ','),
 ("'", ' ', 'y'),
 ('-', 'I', ' '),
 (':', '\n', '_'),
 ('_', '_', '_'),
 ('"', 'b', 'u'),
 ('l', 'd', '?'),
 (' ', '"', 'O'),
 ('\n', 'c', 'a'),
 ('n', 'd', 'y'),
 ('i', 's', '\n'),
 ('\n', 'O', 'u'),
 ('m', ' ', '('),
 ('n', '\n', 'd'),
 ('a', 'r', 'l'),
 ('e', ' ', 's'),
 (' ', ' ', 'i'),
 ('a', 'm', '\n'),
 ('o', 'x', "'"),
 ('u', 'y', ','),
 ('c', 'e', "'"),
 ('d', 'a', 'b'),
 ('d', 'd', '!'),
 ('s', 'e', ','),
 ('e', 'a', 'c'),
 ('m', '"', '-'),
 ('!', ' ', "'"),
 ('n', ';', '\n'),
 ('h', ' ', 'J'),
 ('f', 'a', 'r'),
 ('o', 'n', '"'),
 ('n', 'u', 'r'),
 ('h', '.', ')'),
 ('t', '\n', 'u'),
 ('o', 'x', 'e'),
 (' ', 'g', 'r'),
 (' ', 'I', '?'),
 ('n', 'r', 'y'),
 (' ', '`', 't'),
 ('l', '\n', 'k'),

The following code can be used to compute the jaccard similarity between two sets.

In [6]:
def jaccard(set1, set2):
    return len(set1 & set2)/(len(set1 | set2))

And this code shows how to compute the jaccard similarity between the sets of 3-shingles of two documents in the Gutenberg corpus.

In [7]:
k3_shingle_emma = k_shingles(emma, 3)
persuasion = gutenberg.raw('austen-persuasion.txt')
k3_shingle_persuasion = k_shingles(persuasion, 3)
jaccard(k3_shingle_emma, k3_shingle_persuasion)

0.6289907557419232

### Exercise: 

Fill the following table with the pairwise Jaccard similarities of the first 4 documents of the Gutenberg set. To compute the Jaccard similarities, use their 4-shingle representations. What are the two most similar documents?

|  | austen-emma | austen-persuasion | austen-sense | bible-kjv |
| --- | --- | --- | --- | --- |
| **austen-emma** | | | | |
| **austen-persuasion** | | | | |
| **austen-sense** | | | | |
| **bible-kjv** | | | | |

Repeat the exercise, but now using their 9-shingle representations. Comment on the results. What happened and why?

|  | austen-emma | austen-persuasion | austen-sense | bible-kjv |
| --- | --- | --- | --- | --- |
| **austen-emma** | | | | |
| **austen-persuasion** | | | | |
| **austen-sense** | | | | |
| **bible-kjv** | | | | |

### Exercise:

The following code uses Python's hash() function to define our hash function that maps a shingle to a number within a specific range of values.

In [8]:
def my_hash(item, target_range):
    return hash(item) % target_range

This code illustrates how to use `my_hash`. When you run the cell below you will probably notice a different hash number, but if you run the cell several times in the same python session the number will not change. This is because Python's implementation of hash() does not guarantee the same number in different runs of Python.

In [9]:
my_hash(('a','b','c'), 2**32)

3699954575

The code below uses the hash function to build the k_shingles of a document. It takes as a parameter the text, the value of k, the hash function, and the range of the hash function.

In [10]:
def k_hash_shingles(text, k, hash_function, target_range):
    return set(hash_function(item, target_range) 
               for item in nltk.ngrams(text, k))

In [11]:
k3_hash_shingle_emma = k_hash_shingles(emma, 3, my_hash, 2**32)
k3_hash_shingle_persuasion = k_hash_shingles(persuasion, 3, my_hash, 2**32)
jaccard(k3_hash_shingle_emma, k3_hash_shingle_persuasion)

0.6289907557419232

Using the hash function, represent the first five documents in the Gutenberg corpus as 4-shingles hashed to a range between $0$ and $2^{10}-1$, compute all pairwise jaccard similarities and determine the two documents that are most similar.

1. What are the differences in the results with those of the previous exercise?
2. What are the differences sizes between the 4-shingles and the hashed versions?

## Minhashing

The following code implements a family of different hash functions depending the hash_index.

In [12]:
def permute_hash(item, hash_index, target_range):
    return (hash(item) * (hash_index+1) + 1) % target_range

For example, here are the hash values of two strings for 10 different values of hash_index.

In [13]:
for i in range(10):
    print(permute_hash('a', i, 2**32), permute_hash('b', i, 2**32))

3430464558 1534383903
2565961819 3068767805
1701459080 308184411
836956341 1842568313
4267420898 3376952215
3402918159 616368821
2538415420 2150752723
1673912681 3685136625
809409942 924553231
4239874499 2458937133


The code below builds the signature matrix of the minhash of a list of k-shingles, where we can customize the permute hash function, the number of rows in the final signature matrix, and the target range of the permute hash function.

In [14]:
import numpy as np
def minhash(kshingles,
            permute_hash_function, signature_rows,
            target_range,
            verbose=False):
    sig = np.ones((signature_rows, len(kshingles))) * np.inf
    for r in range(target_range):
        for c, ks in enumerate(kshingles):
            if r not in ks:
                continue
            for i in range(signature_rows):
                sig[i, c] = min(sig[i,c], 
                                permute_hash_function(r, i, target_range))
        if verbose:
            print("After scanning row %i" % r)
            print("Signature matrix:")
            print(sig)
    return sig

Below we can see some code that builds the signature matrix that we have covered in the lectures.

In [15]:
def simple_permute_hash(x, index, target_range):
    if index == 0:
        return (x + 1) % target_range
    else:
        return (3*x + 1) % target_range

In [16]:
kshingles = [{0, 3}, {2}, {1, 3, 4}, {0, 2, 3}]
minhash(kshingles, simple_permute_hash, 2, 5, verbose=True)

After scanning row 0
Signature matrix:
[[  1.  inf  inf   1.]
 [  1.  inf  inf   1.]]
After scanning row 1
Signature matrix:
[[  1.  inf   2.   1.]
 [  1.  inf   4.   1.]]
After scanning row 2
Signature matrix:
[[ 1.  3.  2.  1.]
 [ 1.  2.  4.  1.]]
After scanning row 3
Signature matrix:
[[ 1.  3.  2.  1.]
 [ 0.  2.  0.  0.]]
After scanning row 4
Signature matrix:
[[ 1.  3.  0.  1.]
 [ 0.  2.  0.  0.]]


array([[ 1.,  3.,  0.,  1.],
       [ 0.,  2.,  0.,  0.]])

And below are different signature matrices resulting from different target ranges of the permute hash function using the first 5 documents of the NLTK Gutenberg corpus.

In [17]:
print("Obtaining initial shingles")
target_range = 32
k=4
kshingles = [k_hash_shingles(gutenberg.raw(f), k, 
                            my_hash,
                            target_range) 
             for f in gutenberg.fileids()[:5]]
print("Computing minhash")
minhash(kshingles, permute_hash, 5, target_range)

Obtaining initial shingles
Computing minhash


array([[ 0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [18]:
print("Obtaining initial shingles")
target_range = 3200
k=4
kshingles = [k_hash_shingles(gutenberg.raw(f), k, 
                            my_hash,
                            target_range) 
             for f in gutenberg.fileids()[:5]]
print("Computing minhash")
minhash(kshingles, permute_hash, 5, target_range)

Obtaining initial shingles
Computing minhash


array([[ 0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [19]:
print("Obtaining initial shingles")
target_range = 320000
k=4
kshingles = [k_hash_shingles(gutenberg.raw(f), k,
                            my_hash,
                            target_range) 
             for f in gutenberg.fileids()[:5]]
print("Computing minhash")
minhash(kshingles, permute_hash, 5, target_range)

Obtaining initial shingles
Computing minhash


array([[  3.,   3.,   1.,   2.,  24.],
       [  5.,   5.,   1.,   3.,  11.],
       [  7.,   7.,   1.,   4.,  27.],
       [  9.,   9.,   1.,   5.,  21.],
       [  1.,  11.,   1.,   1.,  46.]])

In [20]:
print("Obtaining initial shingles")
target_range = 32000000
k=4
kshingles = [k_hash_shingles(gutenberg.raw(f), k, 
                            my_hash,
                            target_range) 
             for f in gutenberg.fileids()[:5]]
print("Computing minhash")
minhash(kshingles, permute_hash, 5, target_range)

Obtaining initial shingles
Computing minhash


array([[ 2198.,  2198.,   180.,   180.,  3477.],
       [   25.,  4395.,   359.,    25.,  6953.],
       [  561.,   561.,   538.,   189.,   561.],
       [   49.,  2765.,   717.,    49.,  6505.],
       [  511.,   511.,   896.,   896.,  5156.]])

### Exercise:

Given the following artificially constructed list of sets, compute the pairwise Jaccard similarities.

Now, compute the pairwise Jaccard similarities after calculating the signature matrix using the following code. Compare the results.

In [21]:
def simple_permute_hash(x, index, target_range):
    if index == 0:
        return (x + 1) % target_range
    else:
        return (3*x + 1) % target_range
kshingles = [{0, 3}, {2}, {1, 3, 4}, {0, 2, 3}]
sig = minhash(kshingles, simple_permute_hash, 2, 5)
sig

array([[ 1.,  3.,  0.,  1.],
       [ 0.,  2.,  0.,  0.]])

You will observe that the results are different. Repeat the exercise, now using the first 5 documents of the Gutenberg corpus. What would be a reasonable number of rows of the signature matrix, and a reasonable target range of the hash function, so that the results are fairly accurate and yet the size of the signature matrix is not too large?

## MapReduce

As an optional exercise, write and execute MapReduce code that could be used to find the pairs of documents with jaccard similarity above a given threshold $t$.